[package]
name = "engine_traits"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
error_code = { path = "../error_code" }
hex = "0.4"
protobuf = "2"
quick-error = "1.2.2"
tikv_alloc = { path = "../tikv_alloc" }
tikv_util = { path = "../tikv_util" }
